runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  NODE_ENV: "production"
  PYTHONUNBUFFERED: "1"
  FOUNDARY_HOME: "/root/.foundry"

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 1
  max_idle_instances: 1
  min_idle_instances: 0
  max_instances: 1
  cpu_utilization:
    target_utilization: 0.7
