graph TD
    root --> ./AbstractResolutionStrategy.sol
    root --> ./IPredify.sol
    root --> openzeppelin/contracts/token/ERC20/IERC20.sol
    AbstractResolutionStrategy --> TokenBalanceStrategy
    root --> TokenBalanceStrategy
    root --> openzeppelin/contracts/token/ERC20/IERC20.sol
    root --> ./IPredify.sol
    root --> ./IResolutionStrategy.sol
    root --> openzeppelin/contracts/utils/ReentrancyGuard.sol
    IPredify --> Predify
    ReentrancyGuard --> Predify
    root --> Predify
    root --> openzeppelin/contracts/token/ERC20/IERC20.sol
    root --> ./AbstractResolutionStrategy.sol
    root --> ./IPredify.sol
    AbstractResolutionStrategy --> ManualResolutionStrategy
    root --> ManualResolutionStrategy
    root --> ./IResolutionStrategy.sol
    IResolutionStrategy --> AbstractResolutionStrategy
    root --> AbstractResolutionStrategy
    root --> ./IPredify.sol
    root --> openzeppelin/contracts/token/ERC20/ERC20.sol
    root --> openzeppelin/contracts/access/Ownable.sol
    ERC20 --> MockERC20
    Ownable --> MockERC20
    root --> MockERC20
