# action_validation_analyzer.py
from typing import List, Dict, Optional
from pydantic import BaseModel
from .models import Action, DeploymentInstruction, Contract
from .three_stage_llm_call import ThreeStageAnalyzer
from .context import RunContext
import json
import subprocess
from pathlib import Path

class ActionValidationPlan(BaseModel):
    """Complete validation plan including generated script"""
    target_action: str
    description: str
    validation_script: str  # Full TypeScript code generated by LLM
    expected_checks: List[str]

    def to_dict(self):
        return self.dict()

class ActionValidationResult(BaseModel):
    """Results of action validation"""
    action_name: str
    success: bool
    execution_log: str
    validation_checks: List[Dict]
    errors: List[str] = []

    def to_dict(self):
        return self.dict()

class DynamicActionValidator:
    def __init__(self, context: RunContext):
        self.context = context
    
    def validate_action(self, action: Action) -> ActionValidationResult:
        """Full dynamic validation workflow"""
        # Step 1: Generate complete validation plan with script
        analyzer = DynamicValidationAnalyzer(self.context)
        plan = analyzer.generate_validation_plan(action)
        
        # Step 2: Execute the generated script
        executor = DynamicValidationExecutor(self.context)
        result = executor.execute_validation(plan)
        
        return result

class DynamicValidationAnalyzer:
    def __init__(self, context: RunContext):
        self.context = context
        self.system_prompt = (
            "You are an expert smart contract developer and TypeScript programmer. "
            "Your task is to implement fixes for code review comments in a precise and maintainable way. "
            "Generate a comprehensive, precise, and maintainable Hardhat/TypeScript validation script for the given smart contract action. "
            "Follow best practices, ensure robust error handling, and provide clear comments explaining your logic. "
            "Preserve original functionality, validate all expected state changes, and use ethers.js v6. "
            "Return the complete TypeScript code in the validation_script field."
        )
    
    def generate_validation_plan(self, action: Action) -> ActionValidationPlan:
        """Generate complete validation plan with executable script"""
        # Prepare comprehensive context
        context = self._prepare_full_context(action)
        
        # Generate prompt for complete validation solution
        prompt = self._create_script_generation_prompt(action, context)
        
        # Get complete validation solution from LLM
        analyzer = ThreeStageAnalyzer(ActionValidationPlan, system_prompt=self.system_prompt)
        plan = analyzer.ask_llm(prompt, guidelines=[
            "1. Generate complete executable TypeScript code",
            "2. Include all necessary contract deployments",
            "3. Implement all prerequisite actions",
            "4. Include comprehensive validation checks",
            "5. Use proper error handling and logging",
            "6. Follow Hardhat testing best practices"
        ])
        
        return plan
    
    def _prepare_full_context(self, action: Action) -> Dict:
        """Prepare all context needed for script generation"""
        project = self.context.project_summary()
        deployment = self.context.deployment_instructions()
        actors = self.context.actor_summary()
        
        # Get contract interfaces
        contracts = {}
        for contract in project.contracts:
            with open(self.context.contract_artifact_path(contract.name), 'r') as f:
                abi = json.load(f)['abi']
            
            contracts[contract.name] = {
                "abi": abi,
                "functions": [f for f in abi if f['type'] == 'function'],
                "is_deployable": contract.is_deployable
            }
        
        # Get related actions
        related_actions = []
        for actor in actors.actors:
            for act in actor.actions:
                if act.contract_name == action.contract_name:
                    related_actions.append({
                        "name": act.name,
                        "function": act.function_name,
                        "contract": act.contract_name
                    })
        
        return {
            "action": {
                "name": action.name,
                "contract": action.contract_name,
                "function": action.function_name,
                "summary": action.summary
            },
            "contracts": contracts,
            "deployment_sequence": deployment.to_dict(),
            "related_actions": related_actions,
            "project_type": project.dev_tool
        }
    
    def _create_script_generation_prompt(self, action: Action, context: Dict) -> str:
        """Create prompt for complete validation script generation"""
        return f"""
Generate a complete Hardhat/TypeScript validation script for the action '{action.name}' 
in contract '{action.contract_name}'. The script should:

1. Deploy all required contracts
2. Execute all prerequisite actions
3. Test the target action with realistic parameters
4. Include comprehensive state validation checks
5. Provide detailed logging

Return the complete TypeScript code in the validation_script field.

Guidelines:
- Use ethers.js v6
- Follow Hardhat testing best practices
- Include error handling
- Validate all expected state changes
- Use the deployed contracts from the deployment sequence where possible

Action Details:
{json.dumps(context['action'], indent=2)}

Project Context:
- Project Type: {context['project_type']}
- Contracts: {json.dumps(list(context['contracts'].keys()), indent=2)}

Related Actions:
{json.dumps(context['related_actions'], indent=2)}

Deployment Sequence:
{json.dumps(context['deployment_sequence'], indent=2)}
"""

class DynamicValidationExecutor:
    def __init__(self, context: RunContext):
        self.context = context
    
    def execute_validation(self, plan: ActionValidationPlan) -> ActionValidationResult:
        """Execute the dynamically generated validation script"""
        result = ActionValidationResult(
            action_name=plan.target_action,
            success=False,
            execution_log="",
            validation_checks=[]
        )
        
        try:
            # Save generated script
            script_path = self._save_validation_script(plan)
            
            # Execute script
            logs = self._run_validation_script(script_path)
            
            # Process results
            result.execution_log = logs
            result.success = "Validation completed successfully" in logs
            result.validation_checks = [{
                "description": check,
                "passed": check.lower() in logs.lower()
            } for check in plan.expected_checks]
            
        except Exception as e:
            result.errors.append(str(e))
            result.success = False
        
        return result
    
    def _save_validation_script(self, plan: ActionValidationPlan) -> Path:
        """Save the generated validation script"""
        script_path = Path(self.context.simulation_path()) / "scripts" / f"validate_{plan.target_action}.ts"
        script_path.parent.mkdir(exist_ok=True)
        
        with open(script_path, "w") as f:
            f.write(plan.validation_script)
            
        return script_path
    
    def _run_validation_script(self, script_path: Path) -> str:
        """Execute the validation script and capture output"""
        try:
            result = subprocess.run(
                ["ts-node", str(script_path)],
                cwd=self.context.simulation_path(),
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                timeout=300
            )
            return result.stdout
        except subprocess.CalledProcessError as e:
            return e.stdout
        except Exception as e:
            return str(e)